
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author batu1
 */
public class ticket extends javax.swing.JFrame {

    /**
     * Creates new form ticket
     */
    public ticket() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        konu.setEnabled(false);
        msgalanı.setEnabled(false);
        gönder.setEnabled(false);
        edit.setEnabled(false);
        bilgikadı.setEditable(false);
        bilgieposta.setEditable(false);
        bilgitelefon.setEditable(false);
          
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        konu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        msgalanı = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kadı = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        giris = new javax.swing.JButton();
        gönder = new javax.swing.JLabel();
        edit = new javax.swing.JLabel();
        geri = new javax.swing.JLabel();
        bilgikadı = new javax.swing.JTextField();
        bilgieposta = new javax.swing.JTextField();
        bilgitelefon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sifre = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        konu.setBackground(new java.awt.Color(204, 204, 255));
        konu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Konu :");

        msgalanı.setBackground(new java.awt.Color(204, 204, 255));
        msgalanı.setColumns(20);
        msgalanı.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        msgalanı.setRows(5);
        jScrollPane1.setViewportView(msgalanı);

        jLabel2.setText("Ticket açmak için tekrar giriş yapmanız gerekmektedir.");

        jLabel3.setForeground(new java.awt.Color(102, 255, 255));
        jLabel3.setText("Kullanıcı Adı :");

        jLabel4.setForeground(new java.awt.Color(102, 255, 255));
        jLabel4.setText("Şifre :");

        giris.setBackground(new java.awt.Color(255, 255, 255));
        giris.setText("Giriş");
        giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisActionPerformed(evt);
            }
        });

        gönder.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gönder.setForeground(new java.awt.Color(255, 255, 255));
        gönder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İkon/add.png"))); // NOI18N
        gönder.setText("  Gönder");
        gönder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gönderMouseClicked(evt);
            }
        });

        edit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edit.setForeground(new java.awt.Color(255, 255, 255));
        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İkon/edit.png"))); // NOI18N
        edit.setText("  Ticketlarım/Cevaplarım");

        geri.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        geri.setForeground(new java.awt.Color(255, 255, 255));
        geri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/İkon/delete.png"))); // NOI18N
        geri.setText("  Geri/İptal");
        geri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                geriMouseClicked(evt);
            }
        });

        jLabel5.setText("Bilgileriniz yanlış ise Ticketta bu durumu belirtin veya yönetim ile iletişime geçiniz.");

        jDesktopPane1.setLayer(konu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(kadı, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(giris, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(gönder, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(edit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(geri, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bilgikadı, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bilgieposta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bilgitelefon, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(sifre, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(bilgikadı, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bilgieposta, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bilgitelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(konu))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addContainerGap())
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(kadı)
                                            .addComponent(sifre, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                                        .addGap(111, 111, 111))))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGap(159, 159, 159)
                                        .addComponent(giris))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(gönder)
                                            .addComponent(edit)
                                            .addComponent(geri))))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(konu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(kadı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(giris)
                        .addGap(23, 23, 23)
                        .addComponent(gönder)
                        .addGap(18, 18, 18)
                        .addComponent(edit)
                        .addGap(18, 18, 18)
                        .addComponent(geri)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bilgikadı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bilgieposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bilgitelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geriMouseClicked
        AnaMenü kp = new AnaMenü();
        kp.setVisible(true);
        kp.pack();
        kp.setLocationRelativeTo(null);
        kp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_geriMouseClicked

    private void girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisActionPerformed
        PreparedStatement st;
        ResultSet rs;
        
        String kulad = kadı.getText();
        String şifree = sifre.getText();
        String ticketnumarasi = null;
        String query = "SELECT `ad`, `soyad`, `kullanıcıAdı`, `e_posta`, `telefon`, `okul_no`, `şifre`, `id` FROM `kullanıcılar` WHERE `kullanıcıAdı` = ? AND `şifre` = ?";
        
        try {
            st = My_CNX.getConnection().prepareStatement(query);
            st.setString(1, kulad);
            st.setString(2, şifree);
            rs = st.executeQuery();
            if(rs.next()){
            
                JOptionPane.showMessageDialog(null, "Girişiniz Onaylandı.");
                konu.setEnabled(true);
                msgalanı.setEnabled(true);
                gönder.setEnabled(true);
                edit.setEnabled(true);
                kadı.setVisible(false);
                sifre.setVisible(false);
                jLabel2.setVisible(false);
                jLabel3.setVisible(false);
                jLabel4.setVisible(false);
                giris.setVisible(false);
                bilgikadı.setText(rs.getString(3));
                bilgieposta.setText(rs.getString(4));
                bilgitelefon.setText(rs.getString(5));
            }
            else{
            
                JOptionPane.showMessageDialog(null, "Yanlış kullanıcı adı veya şifre!","Hatalı giriş",2);
                sifre.setText("");
                kadı.setText("");
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(ticket.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_girisActionPerformed

    private void gönderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gönderMouseClicked
        
        PreparedStatement st;
        ResultSet rs;
        String konuu = konu.getText();
        String msgalanıı = msgalanı.getText();
        String kulad = kadı.getText();
        String şifree = sifre.getText();
        String ticketnumarasi = null;
        String query = "SELECT `id` FROM `kullanıcılar` WHERE `kullanıcıAdı` = ? AND `şifre` = ?";
        
        try {
            st = My_CNX.getConnection().prepareStatement(query);
            st.setString(1, kulad);
            st.setString(2, şifree);
            rs = st.executeQuery();
            rs.next();
            ticketnumarasi = rs.getString(1);
            
        } catch (SQLException ex) {
            Logger.getLogger(ticket.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
            if (!checkEposta(ticketnumarasi)){
        PreparedStatement ps;               
        ResultSet ry;
        String queryy = "INSERT INTO `ticket`(`Konu`, `Mesaj`, `Ticketnumarası`) VALUES (?,?,?)";         
        
        try {  
            
            ps = My_CNX.getConnection().prepareStatement(queryy);
            ps.setString(1, konuu);
            ps.setString(2, msgalanıı);
            ps.setString(3, ticketnumarasi);
            
            
            if(ps.executeUpdate() != 0 ){
                        JOptionPane.showMessageDialog(null, "Ticket başarıyla oluşturuldu. Ticket numaranız : "+ticketnumarasi+". Ticket numaranızı lütfen unutmayın!");
                        
                        konu.setEditable(false);
                        msgalanı.setEditable(false);
                        
                        
                    }
                    
                    else{
                        JOptionPane.showMessageDialog(null, "Ticket oluşturulamadı! Bilinmeyen bir hata mevcut.");
                    }            
        } catch (SQLException ex) {
            Logger.getLogger(ticket.class.getName()).log(Level.SEVERE, null, ex);
        }
            }

    }//GEN-LAST:event_gönderMouseClicked
                
        public boolean checkEposta(String ticketnumarasi) {
    
        PreparedStatement st;
        ResultSet rs;
        boolean ticketkontrol_exit = false;
        
        String query = "SELECT `Konu`, `Mesaj` FROM `ticket` WHERE `Ticketnumarası` = ?";
        
        try {
            st = My_CNX.getConnection().prepareStatement(query);
            st.setString(1, ticketnumarasi);
            rs = st.executeQuery();

            if(rs.next()){
                ticketkontrol_exit = true;
                konu.setText(rs.getString(1));
                msgalanı.setText(rs.getString(2));
                konu.setEditable(false);
                msgalanı.setEditable(false);
                JOptionPane.showMessageDialog(null, "Zaten açık bir ticketınız mevcut. Yenisini açabilmeniz için yönetim tarafından cevaplanması gerekir. Ticket numarası : "+ticketnumarasi+". Açtığınız Ticket yandaki alanda gözükecektir.", "Hata", 2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(KayıtPencere.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return ticketkontrol_exit;
    }

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bilgieposta;
    private static javax.swing.JTextField bilgikadı;
    private javax.swing.JTextField bilgitelefon;
    private javax.swing.JLabel edit;
    private javax.swing.JLabel geri;
    private javax.swing.JButton giris;
    private javax.swing.JLabel gönder;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextField kadı;
    private javax.swing.JTextField konu;
    private javax.swing.JTextArea msgalanı;
    private static javax.swing.JPasswordField sifre;
    // End of variables declaration//GEN-END:variables
}
